version: '3.9'
services:
  sentry:
    container_name: sentry
    image: sentry
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - 9000:9000
    depends_on:
      - redis
      - postgres
    tty: true
    stdin_open: true

  cron:
    container_name: sentry-cron
    image: sentry
    platform: linux/amd64
    command: run cron
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  worker:
    container_name: sentry-worker
    image: sentry
    platform: linux/amd64
    command: run worker
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  redis:
    container_name: sentry-redis
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

  postgres:
    container_name: sentry-postgres
    image: postgres
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: secret
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  redis-data:
  pg-data:
